config/routes.rb
Rails.application.routes.draw do
  resources :toppings
  resources :desserts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "desserts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dessert.rb
class Dessert < ApplicationRecord
  has_many :toppings
end

app/models/topping.rb
class Topping < ApplicationRecord
  belongs_to :dessert
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/desserts_controller.rb
class DessertsController < ApplicationController
  before_action :set_dessert, only: %i[ show edit update destroy ]

  # GET /desserts or /desserts.json
  def index
    @desserts = Dessert.all
  end

  # GET /desserts/1 or /desserts/1.json
  def show
  end

  # GET /desserts/new
  def new
    @dessert = Dessert.new
  end

  # GET /desserts/1/edit
  def edit
  end

  # POST /desserts or /desserts.json
  def create
    @dessert = Dessert.new(dessert_params)

    respond_to do |format|
      if @dessert.save
        format.html { redirect_to dessert_url(@dessert), notice: "Dessert was successfully created." }
        format.json { render :show, status: :created, location: @dessert }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dessert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /desserts/1 or /desserts/1.json
  def update
    respond_to do |format|
      if @dessert.update(dessert_params)
        format.html { redirect_to dessert_url(@dessert), notice: "Dessert was successfully updated." }
        format.json { render :show, status: :ok, location: @dessert }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dessert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /desserts/1 or /desserts/1.json
  def destroy
    @dessert.destroy

    respond_to do |format|
      format.html { redirect_to desserts_url, notice: "Dessert was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dessert
      @dessert = Dessert.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dessert_params
      params.require(:dessert).permit(:name)
    end
end

app/controllers/toppings_controller.rb
class ToppingsController < ApplicationController
  before_action :set_topping, only: %i[ show edit update destroy ]

  # GET /toppings or /toppings.json
  def index
    @toppings = Topping.all
  end

  # GET /toppings/1 or /toppings/1.json
  def show
  end

  # GET /toppings/new
  def new
    p params
    @topping = Topping.new
    @topping.dessert_id = params["dessert_id"].to_i
  end

  # GET /toppings/1/edit
  def edit
  end

  # POST /toppings or /toppings.json
  def create
    @topping = Topping.new(topping_params)

    respond_to do |format|
      if @topping.save
        format.html { redirect_to topping_url(@topping), notice: "Topping was successfully created." }
        format.json { render :show, status: :created, location: @topping }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @topping.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /toppings/1 or /toppings/1.json
  def update
    respond_to do |format|
      if @topping.update(topping_params)
        format.html { redirect_to topping_url(@topping), notice: "Topping was successfully updated." }
        format.json { render :show, status: :ok, location: @topping }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @topping.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /toppings/1 or /toppings/1.json
  def destroy
    @topping.destroy

    respond_to do |format|
      format.html { redirect_to toppings_url, notice: "Topping was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topping
      @topping = Topping.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def topping_params
      params.require(:topping).permit(:name, :dessert_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/desserts_helper.rb
module DessertsHelper
end

app/helpers/toppings_helper.rb
module ToppingsHelper
end

app/views/desserts/_dessert.html.erb
<div id="<%= dom_id dessert %>">
  <p>
    <strong>Name:</strong>
    <%= dessert.name %>
  </p>

  <!--Show each dessert topping-->
  <p>
    <strong>Toppings:</strong>
    <ul>
      <% dessert.toppings.each do |topping| %>
        <li><%= topping.name %></li>
      <% end %>
    </ul>

</div>

app/views/desserts/_form.html.erb
<%= form_with(model: dessert) do |form| %>
  <% if dessert.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(dessert.errors.count, "error") %> prohibited this dessert from being saved:</h2>

      <ul>
        <% dessert.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/desserts/edit.html.erb
<h1>Editing dessert</h1>

<%= render "form", dessert: @dessert %>

<br>

<div>
  <%= link_to "Show this dessert", @dessert %> |
  <%= link_to "Back to desserts", desserts_path %>
</div>

app/views/desserts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Desserts</h1>

<div id="desserts">
  <% @desserts.each do |dessert| %>
    <%= render dessert %>
    <p>
      <%= link_to "Show this dessert", dessert %>
    </p>
  <% end %>
</div>

<%= link_to "New dessert", new_dessert_path %>

app/views/desserts/new.html.erb
<h1>New dessert</h1>

<%= render "form", dessert: @dessert %>

<br>

<div>
  <%= link_to "Back to desserts", desserts_path %>
</div>

app/views/desserts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @dessert %>

<div>

  <%= link_to "Add topping", new_topping_path({dessert_id: @dessert}) %>

  <%= link_to "Edit this dessert", edit_dessert_path(@dessert) %> |
  <%= link_to "Back to desserts", desserts_path %>

  <%= button_to "Destroy this dessert", @dessert, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FrozenDesserts</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/toppings/_form.html.erb
<%= form_with(model: topping) do |form| %>
  <% if topping.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(topping.errors.count, "error") %> prohibited this topping from being saved:</h2>

      <ul>
        <% topping.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.hidden_field :dessert_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/toppings/_topping.html.erb
<div id="<%= dom_id topping %>">
  <p>
    <strong>Name:</strong>
    <%= topping.name %>
  </p>

  <p>
    <strong>Dessert:</strong>
    <%= topping.dessert.name %>
  </p>

</div>

app/views/toppings/edit.html.erb
<h1>Editing topping</h1>

<%= render "form", topping: @topping %>

<br>

<div>
  <%= link_to "Show this topping", @topping %> |
  <%= link_to "Back to toppings", toppings_path %>
</div>

app/views/toppings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Toppings</h1>

<div id="toppings">
  <% @toppings.each do |topping| %>
    <%= render topping %>
    <p>
      <%= link_to "Show this topping", topping %>
    </p>
  <% end %>
</div>

<%= link_to "New topping", new_topping_path %>

app/views/toppings/new.html.erb
<h1>New topping</h1>

<%= render "form", topping: @topping %>

<br>

<div>
  <%= link_to "Back to toppings", toppings_path %>
</div>

app/views/toppings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @topping %>

<div>
  <%= link_to "Edit this topping", edit_topping_path(@topping) %> |
  <%= link_to "Back to toppings", toppings_path %> |
  <%= link_to "Back to desserts", desserts_path %>

  <%= button_to "Destroy this topping", @topping, method: :delete %>
</div>